### ISSUE TITLE
What: Error I/O

### ISSUE THREAD

**Issue by Vanessaprd** [a-pavlov/jed2k#10]
I'm connected to the server and this error appears when I click the file from the search, so it does not start downloads. this also happens with kademlia. Please respond :]

**Comment by a-pavlov** [comment]
Hi, most likely it means location you selected for files is not accessible for application. Please try to change location - in options page you will find location setting. For testing purposes you can select not SD card firstly.

**Comment by Vanessaprd** [comment]
Ok now perfect, thanks for app ♡

Il Lun 1 Ott 2018, 06:34 Andrey Pavlov <notifications@github.com> ha
scritto:

**Comment by a-pavlov** [comment]
Great, thank you.
