### ISSUE TITLE
It's a good app but...

### ISSUE THREAD

**Issue by xxsegaxx** [a-pavlov/jed2k#2]
I have 2 problems:The app closes in background after 1 minute and the other problem is...the files doesn't download when I turn off the screen only that and maybe it's just in my phone

**Comment by a-pavlov** [comment]
Most likely Android closed service since it needs more memory - I have similar behaviour. About downloading when screen turned off - it works, application continues download in this case. So, I will investigate service problem and return to you.

**Comment by a-pavlov** [comment]
Seems problems was in advertizement. Partial fix will be in next release, not 100% but dramatically reduce  interruptions count.

**Comment by a-pavlov** [comment]
Fixed version in Google Play

**Comment by xxsegaxx** [comment]
Thanks for the fixed version
