### ISSUE TITLE
Movie Downloads 

### ISSUE THREAD

**Issue by Guytracey** [a-pavlov/jed2k#28]
When I download any movie with "Mule on Android".... The app is putting a .bin extension on the end of the file name which I have to manually remove in order to play the media file... Ie. The Lion King.mkv.bin! So unable to play or view the movie through the app. Any help would be great! Regards

**Comment by a-pavlov** [comment]
At the first look seems that extension was added by DocumentProvider. As I see in the documentation https://developer.android.com/reference/android/support/v4/provider/DocumentFile document provider can add extension to the display name depending on the implementation. Please share the Android version.

**Comment by Guytracey** [comment]
![Screenshot_20200322-221951_Settings](https://user-images.githubusercontent.com/62327888/77251801-67720100-6c8b-11ea-8eae-8601014943a0.jpg)
![Screenshot_20200322-222001_Settings](https://user-images.githubusercontent.com/62327888/77251814-7eb0ee80-6c8b-11ea-8003-89d3814710d7.jpg)

**Comment by Guytracey** [comment]
![Screenshot_20200322-222447_Mule on Android](https://user-images.githubusercontent.com/62327888/77251933-4eb61b00-6c8c-11ea-8588-b47e8e114052.jpg)
![Screenshot_20200322-222635_My Files](https://user-images.githubusercontent.com/62327888/77251942-5ecdfa80-6c8c-11ea-9cfd-bccfac8f9384.jpg)

**Comment by a-pavlov** [comment]
@Guytracey  I've reproduced the problem on Android 10 API 29. Let me think how fix it.

**Comment by Guytracey** [comment]
Thankyou!

**Comment by a-pavlov** [comment]
@Guytracey  I've added trivial fix for names in Android 10. It was added to direct APK link https://drive.google.com/open?id=0B39-MtFuW1DTbW5LUk1IR3lsTGM.

**Comment by superbonaci** [comment]
> @Guytracey I've added trivial fix for names in Android 10. It was added to direct APK link https://drive.google.com/open?id=0B39-MtFuW1DTbW5LUk1IR3lsTGM.

Works fine, could you upload improved version to Google Play Store?

**Comment by tmossy040** [comment]
Why have get permission now to download annoying..
