### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by guba91** [a-pavlov/jed2k#3]
Hi, 
How to improve translation? 
Can we help?

**Comment by a-pavlov** [comment]
Hi, yes of course. All translations here https://github.com/a-pavlov/jed2k/tree/master/android/jdonkey/src/main/res in values-es/strings.xml, values-it/strings.xml and values-ru/strings.xml catalogs. You can fork project and update translations or simply download translation file, update it and send it back. English strings in values/strings.xml. Thank you.
