### ISSUE TITLE
Error. .bin

### ISSUE THREAD

**Issue by tommy0039** [a-pavlov/jed2k#30]
All files downloaded have .bin after the file extension and if i had hair it ripped it out..

Doing it to all grrrr
If I edit file and remove .bin work good.

Dog.jpg.bin

**Comment by tommy0039** [comment]
![20200419_005648](https://user-images.githubusercontent.com/63915968/79641128-de41e180-81d8-11ea-9674-ba2ac04a7c39.jpg)

**Comment by tommy0039** [comment]
![20200419_005620](https://user-images.githubusercontent.com/63915968/79641138-eef25780-81d8-11ea-8c43-a38f46c4053f.jpg)

**Comment by a-pavlov** [comment]
@tommy0039 Looks like this is problem already reported in #28 . Please try fixed version from #28.
