### ISSUE TITLE
Populating the Storage Folder with files from aMule

### ISSUE THREAD

**Issue by cusco-travel-services** [a-pavlov/jed2k#32]
Hi Andrey,

Is it possible to transfer the files from the Temp directory for aMule on my Linux Laptop to what will be the Storage Folder on my Android Phone so that Mule on Android can rehash these files and then continue with the downloads for these files?

Thanks, Michael.

**Comment by a-pavlov** [comment]
Hi Michael,
without coding it is not possible. Mule on Android maintains metadata file for each requested file which contains necessary information about target file. Actually it is not enough to move some partially downloaded file to the targets for Mule - we need hash of this file to obtain original meta information.
