### ISSUE TITLE
Completed downloads removed from list when clicking on Exit

### ISSUE THREAD

**Issue by superbonaci** [a-pavlov/jed2k#34]
When I exit the app from the menu -> Exit, after relaunching Mule, completed downloads no longer appear there. They are still on the filesystem, however.

**Comment by ggn66** [comment]
I have the same problem...please answer us!

**Comment by a-pavlov** [comment]
Please try version 3.0 https://github.com/a-pavlov/jed2k/releases/tag/3.0. If problem still exists please raise the new ticket - I'm planning to add logging to external resources to find the reason with your help. If you ok with it. Thank you.
