### ISSUE TITLE
Direct apk link is v1.6, Releases has v1.7 source No .apk

### ISSUE THREAD

**Issue by juanpc2018** [a-pavlov/jed2k#48]
Direct apk link in About is v1.6 Build 23
https://drive.google.com/open?id=0B39-MtFuW1DTbW5LUk1IR3lsTGM

Releases has v1.7 source No .apk
https://github.com/a-pavlov/jed2k/releases

Android9 App Info say:
version 2.3

**Comment by a-pavlov** [comment]
The new version link directly in github https://github.com/a-pavlov/jed2k/releases/tag/3.0
