### ISSUE TITLE
FIX YOUR APP ON GOOGLE PLAY..

### ISSUE THREAD

**Issue by tmossy040** [a-pavlov/jed2k#50]
Why don't you fix your app on Google Play.. The .bin error annoying the crap out of me.  Instead download from app store like a normal person we have stuff around on a forum it which download a working software, now we have to wait and obtain permission to download the app..

Not rocket science..  Put a copy of app were don't need to waste people time and removing the dam .bin extension on every dam file.

But no you have to make it annoying and get some other developers app which fix your problem from Github Forum.

Why?..

**Comment by a-pavlov** [comment]
Coming soon. The updated version is ready for testing https://github.com/a-pavlov/jed2k/releases/tag/3.0
