### ISSUE TITLE
problem downlading files

### ISSUE THREAD

**Issue by anahoa1** [a-pavlov/jed2k#55]
i downloaded the new version 30 and I'm using android 10
can't download any file it says ( unable to start transfer duo to i/o exception)
![Screenshot_20220207-232146](https://user-images.githubusercontent.com/99219201/152876152-069f276a-7f39-4d1c-b867-7eec5984bc7a.png)

**Comment by a-pavlov** [comment]
Did it work before on older versions or you are new user? This error means the application can not write file to selected destination. Please try to choose another location.

**Comment by anahoa1** [comment]
the old version was working fine .
i have selected several folders but it give me the same error .
i returned to the google play version it's working well .

**Comment by a-pavlov** [comment]
The APK attached to release was updated. Please try again. 
Thank you.
