### ISSUE TITLE
I/O exception 

### ISSUE THREAD

**Issue by igarciamotila** [a-pavlov/jed2k#56]
Hi everyone,
When I try to download a file appears an error message: I/o exception and it's not posible to download anything.
That happens with the latest version from February 2022.

Thanks for your support.

**Comment by G0L14** [comment]
I have the same I/O exception with latest version

**Comment by a-pavlov** [comment]
Hi, this is known issue - #55. Fixed version I've started to rollout on Google Play today, but review process takes a couple of days.
The fixed version is available by direct link here https://github.com/a-pavlov/jed2k/releases/download/3.0/jdonkey-release.apk.
Thank you.

**Comment by igarciamotila** [comment]
Thanks for your effort.
