### ISSUE TITLE
Impossibile selezionare cartella download

### ISSUE THREAD

**Issue by Diabilo701** [a-pavlov/jed2k#59]
Ho aggiornato l'app, adesso non posso scegliere la cartella download e non scarica i files

**Comment by a-pavlov** [comment]
La versione corretta è già disponibile su Google Play. Prova ad aggiornare di nuovo. Grazie.

**Comment by Diabilo701** [comment]
La versione aggiornata e' quella del 9 febbraio 2022.
Non si puo' selezionare la cartella download e quindi non scarica i files

Il 11 febbraio 2022 15:42:05 CET, Andrey Pavlov ***@***.***> ha scritto:
>La versione corretta è già disponibile su Google Play. Prova ad
>aggiornare di nuovo. Grazie.>
>>
>-- >
>Reply to this email directly or view it on GitHub:>
>https://github.com/a-pavlov/jed2k/issues/59#issuecomment-1036280128>
>You are receiving this because you authored the thread.>
>>
>Message ID: ***@***.***>


Inviato dall'app Tiscali Mail.
