### ISSUE TITLE
All the downloads are un pause

### ISSUE THREAD

**Issue by igarciamotila** [a-pavlov/jed2k#60]
Hi,
When I download one or more files, all of them are stopped. The download starts correctly but in a few seconds stops.

Thanks for your support

**Comment by a-pavlov** [comment]
Hi, the files destination is internal storage, not SD card?

**Comment by a-pavlov** [comment]
No, please use SD card. Seems problem in access to internal storage.

**Comment by igarciamotila** [comment]
Hi,
It works properly on sd card but I can't find the downloaded file.
Thanks for your effort

**Comment by igarciamotila** [comment]
Hi again,
I have found the file on my SD card: Android, Data, org.dkf.jmule.
If you download a PDF file, you have to move to your internal storage to read It.

Thanks for your support and your effort

**Comment by a-pavlov** [comment]
Hi, 
I've prepare fast fix for storing files https://github.com/a-pavlov/jed2k/releases/download/3.0/jed2k-android-release-32-b32-basic.apk. Since Android 10 significant changes were introduced to file system access.

**Comment by stefo78** [comment]
I also installed the latest apk but nothing, the files are downloaded, because if I try to open them from the Mule application they work, but I can't find the destination in the phone. Can you help me? Thanks

**Comment by a-pavlov** [comment]
I guess you have something like Android 10 or higher. The problem started from the scoped storage introduced for Android 11
https://developer.android.com/training/data-storage#scoped-storage. In common the application has access only to own files stored under sub directory like Download/Android/data/org.dkf.jmule/files. To solve the problem now you can try to install some kind of file managers with MANAGE_EXTERNAL_STORAGE permissions and use it to search downloaded files.
I'm planning to update the application to add ability to share downloaded media files in Android media library, but it will take some time.
Thank you.

**Comment by a-pavlov** [comment]
Opened the new ticket #61 to track files access problem.

**Comment by a-pavlov** [comment]
The version with initial publishing downloaded files support https://github.com/a-pavlov/jed2k/releases/download/3.3/jed2k-android-release-33-b33-basic.apk. Please let me know if you tried it.
