### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by Ark8585** [a-pavlov/jed2k#64]
After update, mule is set to download to internal storage but file location can not be found.

**Comment by a-pavlov** [comment]
Please let me know about your Android version.

**Comment by Ark8585** [comment]
Android version 12

**Comment by a-pavlov** [comment]
After update the application started to satisfy Android 11 storage updates - an application can write files only to the his sandbox. This is private storage, another application without special permissions can not have the access. https://developer.android.com/about/versions/11/privacy/storage
To see downloaded files you can request to publish them in your media collection using Settings ->Other Settings -> Share media downloads.
