### ISSUE TITLE
Software not appering

### ISSUE THREAD

**Issue by heroku-miraheze** [a-pavlov/jed2k#68]
Software IS not appering.
Appears number, but does not see anything.

**Comment by Zabro321** [comment]
The KAD all the time is 0 please Help me

**Comment by a-pavlov** [comment]
The KAD can be empty if the application can not obtain the starting nodes. Actually it is hard to say what wrong in your particular case. You can try to stop ed2k core and start again to refresh kad nodes. Also KAD must be activated.

**Comment by Zabro321** [comment]
is it to much  to ask if you can update the app and fix the error with Kad
so it doesn't have to be the same error please Thanks

Den sön 4 sep. 2022 10:30iso miso ***@***.***> skrev:
