### ISSUE TITLE
All transfers in waiting source. On Mule V1.2 and on android 6.0.1

### ISSUE THREAD

**Issue by jeanluc2** [a-pavlov/jed2k#7]
Hi,
J am a new user, but 10 years before J used Edonkey during large period.
J was conected at several servers, on router 4661 port is enabled, but all transfers executing are waiting sources.
After connecting at servers, J have a very fast message when J pass on tranfers, begening by "you have a low id ..."  no enough time to read the rest, so J can't understand the peaning of this message..
About low id, J think it's perhaps J have not enough source to offer at others users, J have some sources but never the program Mule asks me about folder of these sources to share.
J have to place my sources on the same Sd card that J use to receive dowloads ?
In the list of servers, under names and addresses J can see about all servers : the terms N/A, why not adapted, J must do something about this to enable them ?
Thank you for any answer
Regards
Jean luc

**Comment by a-pavlov** [comment]
Hi, firstly mule on android only downloads files. Giving out is not implemented. 
    <p>About low id - you will have it if your input port is not accessible outside. If you use router you can manually forward incoming port or do it in preferences. Please check preferences screen - you will find your incoming port and switcher "Forward port". 
    <p>Sources - sorry I didn't catch. Application tries to find sources on server or(and) KAD if Kademlia is active. Of course better to have High ID on server - it will increase available sources count. Unfortunately now only two servers provide good results. One of them is TV Underground. Try to download something popular with more sources to check applications works.
    <p>Saving files - if it was a question - you can choose SD card as destination for your files.
