### ISSUE TITLE
Copy link to clipboard does not generate valid ed2k links sometimes

### ISSUE THREAD

**Issue by superbonaci** [a-pavlov/jed2k#74]
If file name contains spaces or other characters it's not formatted properly to URL encode, for example space to %20
It fails to paste directly in eMule.

**Comment by superbonaci** [comment]
Example link provided by Mule for Android version 34.
````
ed2k://|file|DEFA - Spielfilm - 1956 - Alter Kahn und junge Liebe (DDR, R - Hans Heinrich, DA - Alfred Maack, Erika Dunkelmann, GÃ¶tz George)-.avi|554256222|5E85C8A1C4F47F88C77495695B753064|/
````

**Comment by a-pavlov** [comment]
Emule replaces spaces to %20, "%" to corresponding %25 and bytes > 0x7F to hex. It is not actually url-encoding.
I've added replacement for spaces https://github.com/a-pavlov/jed2k/commit/d47b928268de74c96c75d9570c8625d214872ae7

**Comment by a-pavlov** [comment]
The link to fixed apk https://drive.google.com/file/d/1Pj2Z6HajibvswionZqQEqeJUpYSKEo7u/view?usp=sharing

**Comment by superbonaci** [comment]
Thank you very much, works perfect now!!!
