### ISSUE TITLE
Conn.java :  search-command does not work

### ISSUE THREAD

**Issue by JamesOlvertone** [a-pavlov/jed2k#82]
search2 : works
search <expression> [dataSize n]  : finds always no results

Fix:
Conn.java:
Line number around 290:
s.search(SearchRequest.makeRequest(0, maxSize, 30, 0, "", "", "", 0, 0, searchExpression));

The variant with command search2 has the parameter always set to 0 and this works here too.
Set 30 to 0 and you will get results from the server.

**Comment by a-pavlov** [comment]
Hi, Conn is test application - you can change it as you like.
