### ISSUE TITLE
Upload capability

### ISSUE THREAD

**Issue by itlezy** [a-pavlov/jed2k#84]
Hi first of all great work, this is a really good project.

Do you have plans to add upload capabilities? It would be nice to have a console/daemon uploader to E2K network

Thanks

**Comment by a-pavlov** [comment]
@itlezy Hi, I have no plans to add upload capabilities to jed2k library because it designed mostly to be engine for mobile applications on Android. The console uploader can be created using the project https://github.com/qmule/libed2k.
Thank you.
