### ISSUE TITLE
A Suggestion about making this project more portable.

### ISSUE THREAD

**Issue by katcom** [a-pavlov/jed2k#9]
To makes the project Jedk2 be more useful, it is a good idea to provide API to other programmers such that the libraries in this project could makes their lives much more easier. In theory, it can be done by dividing this project into two parts in term of structure - GUI and a utility library - to a extend that it just need a line of command to download files, as portable as the library Picasso is.

On one hand, GUI part creates visual elements and connects the events made by users to certain utility library's operations, such searching files with key words or clicking to download. The utility library, on the other hand, should open a new thread to do the job behind users, open a new thread to download files or connect to servers or search files.

I think this change would improve this project in term of ability to be re-used in other applications.

**Comment by a-pavlov** [comment]
Hi,
Project structure already in form as you suggested - it contains library and UI part for Android. Library in jed2k/core - you can open it separately on any platform - no need Android SDK or something else. Library project configured with Maven - please open pom.xml. There you can file console application Conn with library usage example. For whole Android application you open gradle file in root - it contains library gradle file.

**Comment by katcom** [comment]
Hi,
  Thank you, your library is helpful, though previously I didn't really get it.
