### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [a-pavlov/jed2k#97]
```
FAILURE: Build failed with an exception.

* Where:

Build file '/home/vagrant/build/org.dkf.jmule/console/build.gradle' line: 26

* What went wrong:

A problem occurred evaluating project ':console'.

> Could not set unknown property 'classifier' for task ':console:fatJar' of type org.gradle.api.tasks.bundling.Jar.
```

Could you please take a look? Thanks!

**Comment by a-pavlov** [comment]
Hi, please provide the command you've used.
The command in jed2k directory works for me:
`gradle assembleBasicRelease` 
But you need keystore file.
Master branch.

**Comment by linsui** [comment]
Which gradle version do you use? There is not `gradle/` in the repo so the latest gradle is used (8.3).

**Comment by linsui** [comment]
We need 7.3.3.
